# Generated by Django 5.0.1 on 2026-08-21 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_course_cover'),
        ('learning', '0001_alumni_and_learning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('course_opened', 'Cours ouvert'), ('content_opened', 'Contenu ouvert'), ('video_started', 'Vidéo démarrée'), ('video_progress', 'Progression vidéo'), ('video_completed', 'Vidéo terminée'), ('lesson_completed', 'Leçon terminée'), ('document_opened', 'Document ouvert'), ('course_commented', 'Commentaire')], db_index=True, max_length=40)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to='academic.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to='learning.courselesson')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to='learning.coursemodule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_learning_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', '-created_at'], name='learning_st_teacher_1559ab_idx'), models.Index(fields=['course', '-created_at'], name='learning_st_course__034c75_idx'), models.Index(fields=['student', '-created_at'], name='learning_st_student_e084c1_idx')],
            },
        ),
    ]
