# Generated by Django 5.0.14 on 2026-08-08 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deposit_id', models.UUIDField(db_index=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('phone', models.CharField(max_length=20)),
                ('provider', models.CharField(max_length=32)),
                ('correspondent', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Accepté'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué'), ('REJECTED', 'Rejeté')], db_index=True, default='PENDING', max_length=16)),
                ('course_ids', models.JSONField(blank=True, default=list)),
                ('pawapay_response', models.JSONField(blank=True, default=dict)),
                ('failure_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
