enum DocumentType {
  supportCours,
  resume,
  pdf,
  word,
  powerpoint,
  image,
  video,
  lien,
  livre,
  tp,
  corrige,
  interrogation,
  examen,
  rapport,
  projet,
  projetTutore,
  tfc,
  memoire,
  these,
  article,
  tutoriel,
  ficheRevision,
  autre,
}

extension DocumentTypeX on DocumentType {
  String get label => switch (this) {
        DocumentType.supportCours => 'Support de cours',
        DocumentType.resume => 'Résumé',
        DocumentType.pdf => 'PDF',
        DocumentType.word => 'Word',
        DocumentType.powerpoint => 'PowerPoint',
        DocumentType.image => 'Image',
        DocumentType.video => 'Vidéo',
        DocumentType.lien => 'Lien',
        DocumentType.livre => 'Livre',
        DocumentType.tp => 'TP',
        DocumentType.corrige => 'Corrigé',
        DocumentType.interrogation => 'Interrogation',
        DocumentType.examen => 'Examen',
        DocumentType.rapport => 'Rapport',
        DocumentType.projet => 'Projet',
        DocumentType.projetTutore => 'Projet tuteuré',
        DocumentType.tfc => 'TFC',
        DocumentType.memoire => 'Mémoire',
        DocumentType.these => 'Thèse',
        DocumentType.article => 'Article',
        DocumentType.tutoriel => 'Tutoriel',
        DocumentType.ficheRevision => 'Fiche de révision',
        DocumentType.autre => 'Autre travail',
      };
}
