# Generated by Django 5.0.14 on 2026-07-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_post_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='moderation_status',
            field=models.CharField(choices=[('pending', "En cours d'examen"), ('approved', 'Validée'), ('rejected', 'Refusée')], db_index=True, default='approved', max_length=16),
        ),
        migrations.AddField(
            model_name='post',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
