# Generated by Django 6.0.7 on 2026-07-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_post_kind_stage_tfc_memoire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('discussion', 'Discussion'), ('question', 'Question'), ('tp', 'TP / TD'), ('summary', 'Résumé de cours'), ('exam', 'Examen corrigé'), ('notes', 'Notes de cours'), ('support', 'Support de cours'), ('rapport', 'Rapport de stage'), ('projet_tutore', 'Projet tuteuré'), ('tfc', 'TFC'), ('memoire', 'Mémoire'), ('alumni_advice', 'Conseil académique'), ('alumni_path', 'Parcours universitaire'), ('alumni_career', 'Parcours professionnel'), ('alumni_tfc', 'Stages / mémoire / TFC'), ('alumni_video', 'Vidéo de conseil')], db_index=True, default='discussion', max_length=32),
        ),
    ]
