# Generated by Django 5.0.14 on 2026-07-18 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('cash', 'Argent / portefeuille'), ('ebook', 'Livre numérique'), ('book', 'Livre physique'), ('premium', 'Abonnement Premium'), ('teacher', 'Contenu professeurs'), ('discount', 'Réduction partenaire'), ('other', 'Autre')], default='other', max_length=20)),
                ('min_points', models.PositiveIntegerField(default=100, help_text='Points minimum pour accéder à la roue.')),
                ('points_cost', models.PositiveIntegerField(default=100, help_text='Points déduits à chaque tour.')),
                ('weight', models.PositiveSmallIntegerField(default=10, help_text='Poids relatif pour le tirage (plus élevé = plus fréquent).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['min_points', 'name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='points_awarded',
            field=models.PositiveIntegerField(default=0, help_text='Points déjà crédités à l’auteur après validation.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, help_text='Cycle universitaire RDC : L1, L2, L3, Master 1, Master 2', max_length=32),
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='academic.rewardprize')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
