# Generated by Django 5.0.14 on 2026-07-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_rewards_and_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='moderation_status',
            field=models.CharField(choices=[('pending', "En cours d'examen"), ('approved', 'Validée'), ('rejected', 'Refusée')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='document',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
