# Generated by Django 5.0.14 on 2026-07-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_sync_document_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_user_suggested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='department',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='is_user_suggested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faculty',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_user_suggested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='university',
            name='is_user_suggested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='False = suggestion utilisateur en attente de validation.'),
        ),
    ]
