# Generated by Django 5.0.1 on 2026-07-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_alter_document_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('support_cours', 'Support de cours'), ('resume', 'Résumé'), ('pdf', 'PDF'), ('word', 'Word'), ('powerpoint', 'PowerPoint'), ('image', 'Image'), ('video', 'Vidéo'), ('lien', 'Lien'), ('livre', 'Livre'), ('tp', 'TP'), ('corrige', 'Corrigé'), ('interrogation', 'Interrogation'), ('examen', 'Examen'), ('rapport', 'Rapport de stage'), ('projet', 'Projet'), ('projet_tutore', 'Projet tuteuré'), ('tfc', 'Travail de Fin de Cycle'), ('memoire', 'Mémoire'), ('these', 'Thèse'), ('article', 'Article scientifique'), ('tutoriel', 'Tutoriel'), ('fiche_revision', 'Fiche de révision'), ('autre', 'Autre travail académique')], default='pdf', max_length=32),
        ),
    ]
