# Generated by Django 5.0.1 on 2026-07-22 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_document_rapport_de_stage_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, help_text='Mots-clés séparés par des virgules', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='moderation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Validé'), ('changes_requested', 'Modification demandée'), ('rejected', 'Rejeté')], db_index=True, default='approved', max_length=32),
        ),
        migrations.AddField(
            model_name='course',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academic.promotion'),
        ),
        migrations.AddField(
            model_name='course',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_name',
            field=models.CharField(blank=True, help_text='Titulaire du cours (saisie libre)', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='estimated_hours',
            field=models.PositiveSmallIntegerField(default=0, help_text='Volume horaire estimé'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, help_text='Cycle / semestre : L1, L2, L3, Master 1, Master 2, S1, S2…', max_length=32),
        ),
        migrations.CreateModel(
            name='CourseValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Soumis'), ('approved', 'Validé'), ('changes_requested', 'Modification demandée'), ('rejected', 'Rejeté')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('domain_slugs', models.CharField(blank=True, help_text='Domaines liés au moment de l’action (slugs CSV)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_validation_actions', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_logs', to='academic.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='domains',
            field=models.ManyToManyField(blank=True, related_name='courses', to='academic.learningdomain'),
        ),
    ]
