# Generated by Django 5.0.1 on 2026-08-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_course_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='unique_visitors',
            field=models.PositiveIntegerField(default=0, help_text='Estimation HyperLogLog des visiteurs distincts'),
        ),
        migrations.AddField(
            model_name='course',
            name='views_hll',
            field=models.BinaryField(blank=True, help_text='Sketch HyperLogLog des visiteurs uniques', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de consultations de la page cours (brut)'),
        ),
    ]
