# Generated by Django 5.0.1 on 2026-10-07 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0015_course_hll_unique_visitors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_free',
            field=models.BooleanField(default=True, help_text='Document gratuit (téléchargement sans achat).'),
        ),
        migrations.AddField(
            model_name='document',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix en USD si le document est payant (is_free=False).', max_digits=8),
        ),
        migrations.CreateModel(
            name='DocumentPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='academic.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'document')},
            },
        ),
    ]
